import os
file1 = open("haneef.txt","r+")
print("")
print("#######   Hello Mr. Haneef  #########")
print("")
print("Output of Read function is ")
print("")
print(file1.read())
print("")
print("")
file1.close() 